Iter13
vagafonov/shortener pull request #13
Opened 2024-04-16 22:30 UTC by vagafonov

2024-04-21 11:12 UTC, arttet requested changes

2024-04-21 11:12 UTC, arttet commented on internal/contract/storage.go
> +	ErrAlreadyExistsInStorage = errors.New("already exists")
SUGGESTION: it would be better if you use an additional package with errors

2024-04-21 11:12 UTC, arttet commented on internal/service/url_service.go
> +	for k, v := range req {
CHANGE REQUEST: you need to do this in the handler.

2024-04-21 11:12 UTC, arttet commented on internal/service/url_service.go
> +	req []request.ShortenBatchRequest,
CHANGE REQUEST: this should be `model` data.

2024-04-21 11:12 UTC, arttet commented on internal/storage/db.go
> +	row := s.connection.QueryRowContext(context.TODO(), q, key)
CHANGE REQUEST: you need to provide a context as a parameter of this function.

P.S. This comment should be applied to every function below.

2024-04-21 11:12 UTC, arttet commented on internal/storage/db.go
> +	q := `SELECT id, short, original FROM url WHERE short = $1`
CLARIFICATION: please build SQL execution plan query cost

2024-04-21 11:12 UTC, arttet commented on internal/storage/db.go
> +		q := `INSERT INTO url (id, short, original) VALUES($1, $2, $3)`
CHANGE REQUEST: please optimize this code.

2024-04-22 22:45 UTC, vagafonov commented on internal/application/application.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
Исправил

2024-04-22 22:45 UTC, vagafonov commented on internal/application/application.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
Исправил

2024-04-22 22:46 UTC, vagafonov commented on internal/application/application.go
> +	validatedRequest, err := validate.NewValidator(a.cnt.GetLogger()).ShortenBatchRequest(buf)
Исправил

2024-04-22 22:46 UTC, vagafonov commented on internal/contract/service_url.go
> +	MakeShortURL(url string, length int) (*entity.URL, error)
Исправил

2024-04-22 22:46 UTC, vagafonov commented on internal/contract/storage.go
> +	ErrAlreadyExistsInStorage = errors.New("already exists")
Исправил

2024-04-22 22:46 UTC, vagafonov commented on internal/service/url_service.go
> +	for k, v := range req {
Исправил

2024-04-22 22:46 UTC, vagafonov commented on internal/service/url_service.go
> +	req []request.ShortenBatchRequest,
Исправил

2024-04-22 22:46 UTC, vagafonov commented on internal/storage/db.go
> +	row := s.connection.QueryRowContext(context.TODO(), q, key)
Исправил

2024-04-22 22:46 UTC, vagafonov commented on internal/storage/db.go
> +	q := `SELECT id, short, original FROM url WHERE short = $1`
Добавил индекс для поля short

2024-04-22 22:47 UTC, vagafonov commented on internal/storage/db.go
> +		q := `INSERT INTO url (id, short, original) VALUES($1, $2, $3)`
Исправил

2024-04-24 09:54 UTC, arttet approved these changes

2024-04-24 09:54 UTC, arttet commented on cmd/shortener/main.go
> +//nolint:funlen
CHANGE REQUEST: please remove it.

2024-04-24 09:54 UTC, arttet commented on cmd/shortener/main.go
> +//nolint:funlen
```suggestion

```

2024-04-24 09:54 UTC, arttet commented on cmd/shortener/migrations/000001_create_table_url.up.sql
> +    short  text,
```suggestion
    short  VARCHAR(8),
```

2024-04-24 09:54 UTC, arttet commented on cmd/shortener/migrations/000001_create_table_url.up.sql
> +    original text
```suggestion
    original VARCHAR(2048)
```

2024-04-24 09:54 UTC, arttet commented on db/migrations/000001_create_table_url.up.sql
> +create table url
CHANGE REQUEST: please DRY

2024-04-24 21:04 UTC, vagafonov commented on cmd/shortener/main.go
> +//nolint:funlen
убрал

2024-04-24 21:04 UTC, vagafonov commented on cmd/shortener/migrations/000001_create_table_url.up.sql
> +    short  text,
изменил

2024-04-24 21:04 UTC, vagafonov commented on cmd/shortener/migrations/000001_create_table_url.up.sql
> +    original text
изменил

2024-04-24 21:04 UTC, vagafonov commented on db/migrations/000001_create_table_url.up.sql
> +create table url
переименовал

2024-04-24 21:19 UTC, merged