Iter25
vagafonov/shortener pull request #33
Opened 2024-08-05 23:32 UTC by vagafonov

2024-08-07 18:45 UTC, arttet requested changes

2024-08-07 18:45 UTC, arttet commented on internal/contract/storage.go
> +type Storage interface { //nolint:interfacebloat
It looks like you need to fix it.

2024-08-07 18:45 UTC, arttet commented on proto/shortener.proto
> +message CreateShortUrlRequest {
```suggestion
message CreateShortUrlRequestV1 {
```

2024-08-07 18:45 UTC, arttet commented on proto/shortener.proto
> +service Users {
```suggestion
service UserServiceV1 {
```

2024-08-07 18:45 UTC, arttet commented on proto/shortener.proto
> +  rpc CreateShortURL(CreateShortUrlRequest) returns (CreateShortUrlResponse);
```suggestion
  rpc CreateShortURLV1(CreateShortUrlRequestV1) returns (CreateShortUrlResponseV1);
```

2024-08-07 18:45 UTC, arttet commented on proto/shortener.proto
> +  string url = 1;
Please add validation https://github.com/bufbuild/protoc-gen-validate

2024-08-07 18:45 UTC, arttet commented on proto/shortener.proto
> +  string ShortURL = 1;
Please add bug lint in CI
https://github.com/bufbuild/buf-lint-action
https://buf.build/docs/ci-cd/setup

2024-08-07 18:45 UTC, arttet commented on proto/shortener.proto
> +option go_package = "shortener/proto";
Please read about layouts
https://buf.build/docs/concepts/modules-workspaces

2024-08-09 22:25 UTC, vagafonov commented on internal/contract/storage.go
> +type Storage interface { //nolint:interfacebloat
Измеил в настройке линтера с 10 на 11. Делать под каждый метод харнилища свой интерфейс в данном случае кажется странным.

2024-08-09 22:25 UTC, vagafonov commented on proto/shortener.proto
> +message CreateShortUrlRequest {
Поправил

2024-08-09 22:25 UTC, vagafonov commented on proto/shortener.proto
> +service Users {
Поправил

2024-08-09 22:26 UTC, vagafonov commented on proto/shortener.proto
> +  rpc CreateShortURL(CreateShortUrlRequest) returns (CreateShortUrlResponse);
Поправил

2024-08-09 22:27 UTC, vagafonov commented on proto/shortener.proto
> +  string url = 1;
Добавил валидацию через protoc. На будущее понял, что лучше использовать buf

2024-08-12 10:51 UTC, arttet commented on internal/contract/storage.go
> +type Storage interface { //nolint:interfacebloat
But that warning is about sth else.
```
Interface bloat (anti-pattern, also called fat interface) is when an interface incorporates too many operations on some data.

A linter that checks length of interface.

The bigger the interface, the weaker the abstraction. (C) Go Proverbs
```

2024-08-12 10:54 UTC, arttet requested changes
Please fix autotests.

![image](https://github.com/user-attachments/assets/fd13e4a5-251a-40a8-853d-903fc2bbf3be)

2024-08-12 10:54 UTC, arttet commented on .github/workflows/buf-lint-action.yaml
> +    - uses: bufbuild/buf-lint-action@v1
![image](https://github.com/user-attachments/assets/48daba98-ccfa-41e1-be54-daed822b463c)

2024-08-12 10:54 UTC, arttet commented on proto/shortener.proto
> +  string url = 1 [(validate.rules).string.uri = true];
Where do you validate it?

2024-08-12 10:54 UTC, arttet commented on proto/shortener.proto
> +  rpc CreateShortURLV1(CreateShortUrlRequestV1) returns (CreateShortUrlResponseV1);
Please add more handlers

2024-08-12 11:06 UTC, vagafonov commented on proto/shortener.proto
> +  string url = 1 [(validate.rules).string.uri = true];
https://github.com/vagafonov/shortener/pull/33/files#diff-ac5857b16b8fee4ba8e8c2c3e819ba2797f50fa051aa480cfdd4a51e62730094R76

2024-08-12 11:08 UTC, vagafonov commented on internal/contract/storage.go
> +type Storage interface { //nolint:interfacebloat
Я понял что большие интерфейсы это плохо и учту на будущее. Сейчас что бы передалать это нужно много переписать всего.

2024-08-12 21:51 UTC, vagafonov commented
> Please fix autotests.
> 
> ![image](https://private-user-images.githubusercontent.com/51746822/357018649-fd13e4a5-251a-40a8-853d-903fc2bbf3be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTk0ODUsIm5iZiI6MTcyMzQ5OTE4NSwicGF0aCI6Ii81MTc0NjgyMi8zNTcwMTg2NDktZmQxM2U0YTUtMjUxYS00MGE4LTg1M2QtOTAzZmMyYmJmM2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIxNDYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZTFmY2FlMzgzOGU0OTNlNjdhYmZlYzdiYWM4MmVjZTkzNmRjMTUxN2MzMjljNzdhY2JlN2NiYjVlNWIyN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J3zXrl9Od5I9sEjF0XF_cqptGFP8uAdRoQEb-T9wE0A)

![Снимок экрана от 2024-08-13 00-42-59](https://github.com/user-attachments/assets/73affbc9-507d-41e3-8098-ad66a6f2e376)
https://github.com/Yandex-Practicum/go-musthave-shortener-tpl/blob/main/.github/workflows/shortenertest.yml#L90

2024-08-12 22:31 UTC, vagafonov commented on .github/workflows/buf-lint-action.yaml
> +    - uses: bufbuild/buf-lint-action@v1
Исправил

2024-08-13 19:21 UTC, arttet approved these changes

2024-08-17 14:13 UTC, merged