Iter5
vagafonov/shortener pull request #5
Opened 2024-03-09 18:07 UTC by vagafonov

2024-03-11 14:48 UTC, arttet requested changes
Please add 
- https://github.com/golangci/golangci-lint
- https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/

2024-03-11 14:48 UTC, arttet commented on config/config.go
> +package config
CHANGE REQUEST: It should be in `internal`

2024-03-11 14:48 UTC, arttet commented on internal/application/application.go
> +		if _, err := res.Write([]byte(a.cnt.config.ResultURL + "/" + shortURL.Short)); err != nil {
SUGGESTION: Please use `fmt.Sprintf`

2024-03-11 14:48 UTC, arttet commented on pkg/storage/storage.go
> +package storage
SUGGESTION: It would be better if it is in the application layout.

2024-03-11 14:48 UTC, arttet commented on pkg/entity/url.go
> +package entity
Nitpick: entities are not dto

2024-03-11 14:48 UTC, arttet commented on internal/application/application.go
> +		panic(err)
CHANGE REQUEST: it would be better if you return an error

2024-03-11 18:00 UTC, vagafonov commented on internal/application/service.go
> +type Service struct {
Зачем сервис делать интерфейсом ? Тут используется конкретная бизнес логика.

2024-03-11 18:01 UTC, vagafonov commented on pkg/hasher/hasher.go
Структура сервиса ? Почему ?

2024-03-11 18:07 UTC, vagafonov commented on pkg/storage/memory.go
> +func NewMemoryStorage() *MemoryStorage {
Зачем в конкретном сторадже делать возврат интерфейса ?

2024-03-11 18:08 UTC, vagafonov commented on pkg/storage/storage.go
> +package storage
Не понимаю почему не в pkg ?

2024-03-11 18:08 UTC, vagafonov commented on pkg/entity/url.go
> +package entity
Не понял

2024-03-11 18:20 UTC, vagafonov commented on cmd/client/main.go
> +		panic(err)
Fixed

2024-03-11 18:21 UTC, vagafonov commented on cmd/shortener/main.go
> +	parseFlags()
Исправил и создал отдельный файл для env

2024-03-11 18:21 UTC, vagafonov commented on config/config.go
> +package config
Перенес

2024-03-11 18:22 UTC, vagafonov commented on internal/application/application.go
> +		if _, err := res.Write([]byte(a.cnt.config.ResultURL + "/" + shortURL.Short)); err != nil {
Исправил

2024-03-11 18:22 UTC, vagafonov commented on internal/application/application.go
> +		if _, err := res.Write([]byte(a.cnt.config.ResultURL + "/" + shortURL.Short)); err != nil {
Исправил

2024-03-11 18:22 UTC, vagafonov commented on internal/application/application.go
> +	if shortURL == nil {
Исправил

2024-03-11 18:22 UTC, vagafonov commented on internal/application/application.go
> +		panic(err)
Исправил

2024-03-11 18:30 UTC, vagafonov commented
golangci-lint  с дефолтными линтреами не находит ошибок.
Зачем что то устанавлвать для оценки покрытия если с этим справляется IDE ?

2024-03-13 05:50 UTC, vagafonov commented on pkg/hasher/hasher.go
Исправил

2024-03-13 05:50 UTC, vagafonov commented on pkg/storage/memory.go
> +func NewMemoryStorage() *MemoryStorage {
Исправил

2024-03-13 05:50 UTC, vagafonov commented on pkg/storage/storage.go
> +package storage
Исправил

2024-03-13 14:48 UTC, arttet requested changes
Please add the following actions in CI
- https://golangci-lint.run/usage/install/#ci-installation
- https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/

2024-03-13 14:48 UTC, arttet commented on cmd/client/main.go
> +		log.Fatal(err) //nolint:gocritic
CHANGE REQUEST: please fix it

2024-03-13 14:48 UTC, arttet commented on cmd/client/main.go
> +		log.Fatal(err) //nolint:gocritic
CLARIFICATION: please read docs about `log.Fatal`

2024-03-13 14:48 UTC, arttet commented on cmd/client/main.go
> +		log.Fatal(err)
SUGGESTION: it would be better if you don't use `os.Exit`

2024-03-13 14:48 UTC, arttet commented on cmd/shortener/main.go
> +var options struct {
CHANGE REQUEST: please don't use global variables

2024-03-13 14:48 UTC, arttet commented on internal/application/application.go
> +	if string(body) == "" {
CHANGE REQUEST: please use `go` style

```
	if len(body) == 0 {
		res.WriteHeader(http.StatusBadRequest)
                return

	}
```

2024-03-13 14:48 UTC, arttet commented on .golangci.yml
> +linters:
CHANGE REQUEST: please add it in CI

2024-03-13 17:56 UTC, vagafonov commented on internal/application/service.go
> +type Service struct {
Исправил

2024-03-13 17:56 UTC, vagafonov commented on cmd/client/main.go
> +		log.Fatal(err) //nolint:gocritic
Исправил на log.Panic

2024-03-13 17:58 UTC, vagafonov commented on cmd/client/main.go
> +		log.Fatal(err)
Исправил

2024-03-13 17:59 UTC, vagafonov commented on cmd/shortener/main.go
> +var options struct {
Исправил

2024-03-13 17:59 UTC, vagafonov commented on internal/application/application.go
> +	if string(body) == "" {
Исправил

2024-03-18 14:53 UTC, merged